- name: Inatsll Nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if RHEL
    ansible.builtin.debug:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install nginx if Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os__family == "Debian"

